public enum SyntaxKind
{
    // Tokens
    EndOfFileToken,
    EndOfStatementToken,
    EndOfLineToken,
    CommentaryToken,
    BadToken,
    WhiteSpaceToken,
    NumberToken,
    StringToken,
    IdentifierToken,

    // Symbol Tokens
    OpenBracketToken,
    CloseBracketToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    CommaToken,
    EllipsisToken,
    UnderscoreToken,

    // Operator Tokens
    PlusToken,
    MinusToken,
    StarToken,
    DivToken,
    PercentToken,
    CircumflexToken,
    AtToken,
    EqualEqualToken,
    BangEqualToken,
    GreaterEqualToken,
    LessEqualToken,
    LessToken,
    GreaterToken,
    AmpersandToken,
    PipeToken,
    EqualsToken,
    BangToken,

    // Keywords
    LetKeyword,
    InKeyword,
    IfKeyword,
    ThenKeyword,
    ElseKeyword,
    ConstantKeyword,
    ColorKeyword,
    RestoreKeyword,
    ImportKeyword,
    DrawKeyword,
    LineKeyword,
    SegmentKeyword,
    RayKeyword,
    ArcKeyword,
    CircleKeyword,
    MeasureKeyword,
    IntersectKeyword,
    CountKeyword,
    RandomsKeyword,
    PointsKeyword,
    SamplesKeyword,
    PointKeyword,
    SequenceKeyword,
    PredefinedFunctionKeyword,
    PrintKeyword,

    //Colors
    BlueKeyword,
    RedKeyword,
    YellowKeyword,
    GreenKeyword,
    CyanKeyword,
    MagentaKeyword,
    WhiteKeyword,
    GrayKeyword,
    BlackKeyword,
}
